### ISSUE TITLE
nuxtServerInit is never called

### ISSUE THREAD

**Issue by F145h** [nuxt/create-nuxt-app#229]
generate nuxt project with express, add **store/index.js** with **nuxtServerInit**:

```
import axios from 'axios'
import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export const state = () => {
    return {
    }
}

export const mutations = {

}

export const  actions = {
    // nuxtServerInit is called by Nuxt.js before server-rendering every page
    async nuxtServerInit({dispatch, commit}, {req}) {
        console.log("nuxtServerInit()");
    },
    async test({ commit }, { v }) {
        console.log('store test: ', v)
    }
  }

```

but method test() runs fine from this.$store.dispatch('test'...)

probably nuxtServerInit() never called from nuxt.render

**Comment by F145h** [comment]
need select "Choose rendering mode" as "Universal"

**Comment by j172993563** [comment]
@F145h Thanks.The issue was occurred as you said. I changed the mode from 'spa' to "Universal" in nuxt.config.js. The problem was solved.

**Comment by ButsAndCats** [comment]
Oh wow, it took me so long to find this. Would be awesome to get this documented on this page: https://nuxtjs.org/guide/vuex-store/#modules-mode Is there somewhere I can contribute to the documentation?

**Comment by mavinemvento** [comment]
im using universal mode but nuxtserver action is not still executed

**Comment by khahantk** [comment]
If you are using the Modules mode of the Vuex store, only the primary module (in store/index.js) will receive this action. You'll need to chain your module actions from there.

**Comment by iloyos** [comment]
Hi,

I have the nuxtServerInit in the store/index.js file, the mode: 'universal' and it is still not executed... Any ideas?

**Comment by renardsas** [comment]
@iloyos , I think your problem comes from the config file (nuxt.config.js):
```json
/*
** ssr
** @see https://go.nuxtjs.dev/ssr-mode
** / 
{ 
  ssr: false
}
```
=> Doc : https://nuxtjs.org/guides/configuration-glossary/configuration-ssr
Set it to true and that will solve your problem.
I don't know why but since an update this parameter is false by default
